[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
crate-type = ["cdylib", "rlib"]


[dependencies]
gloo-net = "0.6.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.43"
yew = { version = "0.21.0", features = ["csr"] }
